name: 同步镜像到阿里云 ACR

on:
  schedule:
    - cron: '0 0 * * 0'      # 每周日 0 点自动同步
  workflow_dispatch:            # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login -u liutao4866 --password-stdin crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Sync dockge
        run: |
          docker pull louislam/dockge:latest
          docker tag louislam/dockge:latest crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:dockge-latest
          docker push crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:dockge-latest

      - name: Sync nginx
        run: |
          docker pull nginx:latest
          docker tag nginx:latest crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:nginx-latest
          docker push crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:nginx-latest

      - name: Sync maxkb
        run: |
          docker pull 1panel/maxkb
          docker tag 1panel/maxkb crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:maxkb-latest
          docker push crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:maxkb-latest

      # 以后加新镜像在这下面
      # - name: Sync immich
      #   run: |
      #     docker pull ghcr.io/immich-app/immich-server:latest
      #     docker tag ... crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:immich-server-latest
      #     docker push crpi-t10dpwybj22etm56.cn-hangzhou.personal.cr.aliyuncs.com/liut-2606/liut-docker:immich-server-latest
